-- ProblemSet<01>, JULY <31> <2018>
-- Submission by <s.c.palanichamy@accenture.com> 


1.List full details of all hotels.

SELECT H.HOTEL_NO,H.NAME,H.CITY,R.ROOM_NO,R.HOTEL_NO,R.TYPE,R.PRICE FROM HOTEL H INNER JOIN ROOM R WHERE H.HOTEL_NO=R.HOTEL_NO;

H437|CLAIRMONT HOTEL|BOSTON|223|H437|N|155
H437|CLAIRMONT HOTEL|BOSTON|257|H437|N|140
H111|EMPIRE HOTEL|NEW YORK|313|H111|S|145
H498|JAMES PLAZA|TORONTO|345|H498|N|160
H111|EMPIRE HOTEL|NEW YORK|412|H111|N|145
H498|JAMES PLAZA|TORONTO|467|H498|N|180
H432|BROWNSTONE HOTEL|TORONTO|876|H432|S|124
H432|BROWNSTONE HOTEL|TORONTO|898|H432|S|124
H193|DEVON HOTEL|BOSTON|1001|H193|S|150
H193|DEVON HOTEL|BOSTON|1201|H193|N|175
H235|PARK PLACE|NEW YORK|1267|H235|N|175
H235|PARK PLACE|NEW YORK|1289|H235|N|195

record count 12

2.List full details of all hotels in New York.

SELECT H.HOTEL_NO,H.NAME,H.CITY,R.ROOM_NO,R.HOTEL_NO,R.TYPE,R.PRICE FROM HOTEL H INNER JOIN ROOM R WHERE H.HOTEL_NO=R.HOTEL_NO AND H.CITY='NEW YORK';

H111|EMPIRE HOTEL|NEW YORK|313|H111|S|145
H111|EMPIRE HOTEL|NEW YORK|412|H111|N|145
H235|PARK PLACE|NEW YORK|1267|H235|N|175
H235|PARK PLACE|NEW YORK|1289|H235|N|195

record count 4

3.List the names and cities of all guests, ordered according to their cities.

SELECT NAME,CITY FROM GUEST ORDER BY CITY;

ROBERT SWIFT|ATLANTA
TARA CUMMINGS|BALTIMORE
EDWARD CANE|BALTIMORE
TOM HANCOCK|PHILADELPHIA
ADAM WAYNE|PITTSBURGH
VANESSA PARRY|PITTSBURGH

record count 6

4.List all details for non-smoking rooms in ascending order of price.

SELECT * FROM ROOM WHERE TYPE='N' ORDER BY PRICE;

257|H437|N|140
412|H111|N|145
223|H437|N|155
345|H498|N|160
1201|H193|N|175
1267|H235|N|175
467|H498|N|180
1289|H235|N|195

record count 8

5.List the number of hotels there are.

SELECT COUNT(*) FROM HOTEL;

6

record count 1

6.List the cities in which guests live. Each city should be listed only once.

SELECT DISTINCT CITY FROM GUEST ;

PITTSBURGH
BALTIMORE
PHILADELPHIA

record count 3

7.List the average price of a room.

SELECT AVG(PRICE) AS AVG FROM ROOM;

155.666666666667

record count 1

8.List hotel names, their room numbers, and the type of that room.

SELECT H.NAME,R.ROOM_NO,R.TYPE FROM HOTEL H INNER JOIN ROOM R WHERE H.HOTEL_NO=R.HOTEL_NO;

CLAIRMONT HOTEL|223|N
CLAIRMONT HOTEL|257|N
EMPIRE HOTEL|313|S
JAMES PLAZA|345|N
EMPIRE HOTEL|412|N
JAMES PLAZA|467|N
BROWNSTONE HOTEL|876|S
BROWNSTONE HOTEL|898|S
DEVON HOTEL|1001|S
DEVON HOTEL|1201|N
PARK PLACE|1267|N
PARK PLACE|1289|N

record count 12

9.List the hotel names, booking dates, and room numbers for all hotels in New York.

SELECT NAME,DATE_FROM, ROOM_NO FROM HOTEL H INNER JOIN BOOKING B WHERE H.HOTEL_NO=B.HOTEL_NO AND H.CITY='NEW YORK';

EMPIRE HOTEL|10-AUG-99|412
EMPIRE HOTEL|18-AUG-99|412
PARK PLACE|05-SEP-99|1267

record count 3

10.What is the number of bookings that started in the month of September?
 
SELECT COUNT(GUEST_NO) FROM BOOKING WHERE DATE_FROM LIKE '__-SEP-99' ;

4

record count 1

11.List the names and cities of guests who began a stay in New York in August.

SELECT G.NAME,G.CITY FROM GUEST G INNER JOIN BOOKING B ON G.GUEST_NO=B.GUEST_NO WHERE DATE_FROM LIKE '__-AUG-99' AND B.HOTEL_NO IN(SELECT HOTEL_NO FROM HOTEL WHERE CITY='NEW YORK');

ADAM WAYNE|PITTSBURGH
TARA CUMMINGS|BALTIMORE

record count 2

12.List the hotel names and room numbers of any hotel rooms that have not been booked.

SELECT H.NAME,R.ROOM_NO FROM HOTEL H INNER JOIN ROOM R ON H.HOTEL_NO=R.HOTEL_NO WHERE R.ROOM_NO NOT IN (SELECT ROOM_NO FROM BOOKING);

CLAIRMONT HOTEL|257
EMPIRE HOTEL|313
BROWNSTONE HOTEL|876
BROWNSTONE HOTEL|898
PARK PLACE|1289

record count 5

13.List the hotel name and city of the hotel with the highest priced room.

SELECT NAME,CITY FROM HOTEL WHERE HOTEL_NO=(SELECT HOTEL_NO FROM ROOM WHERE PRICE=(SELECT MAX(PRICE) FROM ROOM));

PARK PLACE|NEW YORK

record count 1

14.List hotel names, room numbers, cities, and prices for hotels that have rooms with prices lower than the lowest priced room in a Boston hotel.

SELECT H.NAME,R.ROOM_NO,H.CITY,R.PRICE FROM HOTEL H INNER JOIN ROOM R ON H.HOTEL_NO=R.HOTEL_NO WHERE R.PRICE<( SELECT MIN(PRICE) FROM ROOM WHERE HOTEL_NO IN(SELECT HOTEL_NO FROM HOTEL WHERE CITY='BOSTON'));

BROWNSTONE HOTEL|876|TORONTO|124
BROWNSTONE HOTEL|898|TORONTO|124

record count 2

15.List the average price of a room grouped by city.

SELECT AVG(PRICE) AS AVG, H.CITY FROM HOTEL H INNER JOIN ROOM R WHERE H.HOTEL_NO=R.HOTEL_NO GROUP BY H.CITY;

155.0|BOSTON
165.0|NEW YORK
147.0|TORONTO

record count 3
